version: '3.8'

services:
  backend:
    build:
      context: ./backend/PokeApi_backend
    ports:
      - "8000:80"

  frontend:
    build:
      context: ./frontend/pokemon-app
    ports:
      - "8080:80"
    depends_on:
      - backend
